import XCTest
@testable import MihonCore

/// These run on Windows/Linux with `swift test` — no Mac, no simulator, no CI.
/// That is the whole point of the platform-agnostic core.
final class SourceIDTests: XCTestCase {

    // MARK: Properties that must hold regardless of the exact hash

    func testIsDeterministic() {
        let a = SourceID.generate(name: "MangaDex", lang: "en", versionId: 1)
        let b = SourceID.generate(name: "MangaDex", lang: "en", versionId: 1)
        XCTAssertEqual(a, b)
    }

    func testSignBitIsAlwaysCleared() {
        // Kotlin `and Long.MAX_VALUE` guarantees a non-negative result.
        for i in 0..<200 {
            let id = SourceID.generate(name: "Source\(i)", lang: "en", versionId: i)
            XCTAssertGreaterThanOrEqual(id, 0, "sign bit must be cleared")
        }
    }

    func testDistinctInputsProduceDistinctIDs() {
        let ids = Set([
            SourceID.generate(name: "MangaDex", lang: "en", versionId: 1),
            SourceID.generate(name: "MangaDex", lang: "ja", versionId: 1),
            SourceID.generate(name: "MangaDex", lang: "en", versionId: 2),
            SourceID.generate(name: "Manga Ball", lang: "en", versionId: 1),
        ])
        XCTAssertEqual(ids.count, 4, "different keys should not collide")
    }

    func testNameIsLowercasedBeforeHashing() {
        // Parity: the Kotlin key lowercases the name, so case must not matter.
        let lower = SourceID.generate(name: "mangadex", lang: "en", versionId: 1)
        let mixed = SourceID.generate(name: "MangaDex", lang: "en", versionId: 1)
        XCTAssertEqual(lower, mixed)
    }

    // MARK: Golden vectors — the ONLY test that truly proves R4 parity

    /// TODO(R4): pin real IDs generated by Mihon and assert them here, then
    /// extend to all 2,016 index source entries. Until these golden vectors
    /// exist, parity is asserted by construction (the algorithm mirrors
    /// HttpSource.kt) but NOT verified. Do not consider R4 closed until this
    /// test has real expected values.
    func testGoldenVectors_pending() throws {
        throw XCTSkip("Populate with real Mihon-generated source IDs (plan R4).")
    }
}
